### PR TITLE
Reimplementation of the install-flox-action as JS Github Action

### PR DESCRIPTION
**Pull request by garbas**
This PR address 3 things:
- Uses flox installer and does not depend on `cachix/install-nix-action`
- We upload only the diff of what was downloaded and/or built.
- Post steps (eg. upload of cache, ...) are automatically ran and a user
  does not have to copy/paste more than one step from the README.

Fixes flox/product#496
Fixes flox/product#508
Fixes flox/product#509

### CODE REVIEW

**Comment by aakropotkin** [comment]
Is it still possible to set the version of Nix?

**Comment by garbas** [comment]
@aakropotkin Is there any reason why you would want 2 different version of Nix?

**Comment by aakropotkin** [comment]
> @aakropotkin Is there any reason why you would want 2 different versions of Nix?

Really I'm interested in ensuring my nix version does not unexpectedly change between two runs without any recorded change in the repository.

We had issues with this last week that caused difficult to debug auth failures that were not reproducible.

**Comment by aakropotkin** [comment]
But also yes we have reasons to use multiple versions of Nix. Long term we'd like to align on one, but for now we do have a need to use multiple versions.

**Comment by garbas** [comment]
> > @aakropotkin Is there any reason why you would want 2 different versions of Nix?
> 
> Really I'm interested in ensuring my nix version does not unexpectedly change between two runs without any recorded change in the repository.
> 
> We had issues with this last week that caused difficult to debug auth failures that were not reproducible.

Oh I see. That is impossible to happen now that we switched to flox installers. Since flox installer remove nix if it is alreadt installed on the system and installs nix that is bundled with flox.

**Comment by garbas** [comment]
> But also yes we have reasons to use multiple versions of Nix. Long term we'd like to align on one, but for now we do have a need to use multiple versions.

For this we'll just produce different installers and run it here. That shouldn't be a problem once we have release pipeline in order. Hopefully still this sprint.

**Review by aakropotkin — APPROVED** [review]
LGTM

**Comment by garbas** [comment]
Just a comment why I didn't merge this work yet. I'm trying to get `flox/flox` to work with this branch, but I have to fix some failures with MacOS first.

**Review by bryanhonof — APPROVED** [review]
PR is fairly large, but the parts that I understood looks good to me.

**Pull request merged**
